{{- $releaseName := .Release.Name }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-secret
stringData:
  HORSE_JOCKEY_USERNAME: {{ .Values.jockey.username }}
  HORSE_JOCKEY_PASSWORD: {{ .Values.jockey.password }}
  HORSE_CLUSTER_SECRET: {{ .Values.cluster.sharedSecret }}