{{- $releaseName := .Release.Name }}
{{- $horsePort := int .Values.server.port }}
{{- $websocketPort := int .Values.server.websocketPort }}
{{- $jockeyPort := int .Values.jockey.port }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}
spec:
  type: ClusterIP
  selector:
    app: {{ $releaseName }}
  ports:
    - protocol: TCP
      name: horse-messaging
      port: 2626
      targetPort: {{ $horsePort }}
    - protocol: TCP
      name: horse-jockey
      port: 2627
      targetPort: {{ $jockeyPort }}
    - protocol: TCP
      name: websocket
      port: 2680
      targetPort: {{ $websocketPort }}
---
{{- range $i, $e := until (int .Values.cluster.replica) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $i }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: {{ $releaseName }}-{{ $i }}
  ports:
    - protocol: TCP
      name: horse-messaging
      port: 2626
      targetPort: {{ $horsePort }}
    - protocol: TCP
      name: horse-jockey
      port: 2627
      targetPort: {{ $jockeyPort }}
    - protocol: TCP
      name: websocket
      port: 2680
      targetPort: {{ $websocketPort }}
---
{{- end }}